Feature/first random app foldas
martinmatejovsky/uceni-javascriptu pull request #5
Opened 2024-12-28 09:24 UTC by Foldass

2024-12-29 10:33 UTC, martinmatejovsky requested changes

2024-12-29 10:33 UTC, martinmatejovsky commented on pages/guitar-chords-trainer.html
> +    <section id="app">
navrhuju přesunout obě sekce z řádku 31 a 33 výše a vnořit je do \<main\>. To proto, že sekce jsou součástí "hlavní" pasáže stránky. do \<main\> můžeš přesunout i spouštěcí tlačítko. A \<footer\> zrušit úplně, protože se zdá, že v aplikaci není nic, co by svým smyslem byla "patička" stránky (třeba copyright, odkaz na obchodní podmínky, spodní navigace...).

2024-12-29 10:33 UTC, martinmatejovsky commented on scripts/ChordsApp/guitarChordsApp.js
> +let firstClick = function () {
Jak se staví k nápadu přejmenovat firstClick na clickStart?

2024-12-29 10:33 UTC, martinmatejovsky commented on scripts/ChordsApp/guitarChordsApp.js
> +  buttonStart.removeEventListener("click", firstClick);
pro inspiraci, jak jinak je možné kontrolovat start/stop, abys nemusel používat removeEventListener( ): po kliknutí na tlačítko se zkontroluje, jestli je nějaká hodnota v proměnné intervalID. Pokud ne, tak z toho poznáš, že aplikace zrovna neběží, a tlačítko provede startovací procesy. Jinak provede stop procesy.

Nebo se také dělá, že v aplikaci bude definovaná proměnná
appIsRunning = false;
a když se klikne na tlačítko, tak se zkontroluje if (appIsRunning) a podle toho se buď spustí startovací procesy + přenastaví se appIsRunning na TRUE, a nebo naopak.

Tolik nápady do budoucna, nemusíš to předělávat nyní.

2024-12-29 10:33 UTC, martinmatejovsky commented on pages/guitar-chords-trainer.html
> +    <!--<meta name="viewport" content="width=device-width, initial-scale=1.0">-->
jsi si jistý, že tohle nepoužijeme? Hodí se to, aby stránka byla dobře čitelná i na mobilním zařízení.

2024-12-29 10:33 UTC, martinmatejovsky commented on scripts/riddles/session-11.js
> +    "Ty neotravovat Jolanda zbytečně a bo nerozhodný, dostat " +
"bo"! To mě pobavilo

2024-12-30 19:54 UTC, Foldass commented on scripts/ChordsApp/guitarChordsApp.js
> +let firstClick = function () {
Velmi pozitivně. Ideu jsem přijal hned, jak jsi ji zmínil napoprvé, jen jsem neprovedl úpravu.

2024-12-30 19:57 UTC, Foldass commented on scripts/ChordsApp/guitarChordsApp.js
> +let firstClick = function () {
Opraveno.

2024-12-30 20:00 UTC, Foldass commented on pages/guitar-chords-trainer.html
> +    <!--<meta name="viewport" content="width=device-width, initial-scale=1.0">-->
tohle mi zůstalo omylem v komentu, když jsem se snažil provázat tlačítko s přiřazením funkce a fur tto nechtělo fungovat a bylo to tím, že jsem byl o složku výše. Dík.

2024-12-30 20:05 UTC, Foldass commented on pages/guitar-chords-trainer.html
> +    <section id="app">
Děkuji. Provedeno, Upraveno

2024-12-30 20:06 UTC, Foldass commented on scripts/ChordsApp/guitarChordsApp.js
> +  buttonStart.removeEventListener("click", firstClick);
Díky za info.

2025-01-01 11:20 UTC, martinmatejovsky approved these changes

2025-01-01 11:44 UTC, closed without merging